baseURL = "https://www.microbreaks.co/"
title = "MicroBreaks.co Blog"
theme = "paper"
languageCode = 'en-us'

[Params]
    mainSections = ["posts"]
    intro = true
    headline = "My headline"
    description = "My description"
    twitter = "jasperschoormns"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
